---- MODULE LateTimer ----
(***************************************************************************)
(* Intentionally weakened variant of spec/PaxosLease.tla, generated by      *)
(* scripts/generate_variants.py.  Do not edit by hand.                      *)
(*                                                                          *)
(* Weakened rule: the proposer starts its pending deadline when it has a    *)
(* prepare quorum in hand and is about to send accept requests (step 3 of   *)
(* the pseudocode in the original 2012 PaxosLease paper), instead of when   *)
(* it sends Prepare.  Nothing then bounds the age of a prepare quorum, so   *)
(* acceptor crash and restart cannot be made safe by any finite quarantine. *)
(* TLC violates LeaseExclusivity under LateTimer.cfg even though the        *)
(* configuration uses the full quarantine bound.                            *)
(***************************************************************************)
EXTENDS Naturals, FiniteSets

CONSTANTS
    Proposers,
    Acceptors,
    Ballots,
    NoOwner,
    MaxTime,
    ProposerDuration,
    AcceptorDuration,
    Quarantine,
    AllowCrash,
    AllowRelease,
    AllowDrop,
    AllowRenewal,
    AllowAbandon,
    AllowRedeliver,
    CrashDropsIncoming,
    RefuseLiveOverwrite,
    MaxNetwork

ASSUME NoOwner \notin Proposers
ASSUME 0 \notin Ballots
ASSUME ProposerDuration <= AcceptorDuration
(***************************************************************************)
(* Safe configurations additionally require                                 *)
(*     Quarantine >= ProposerDuration.                                       *)
(* That assumption lives in PaxosLeaseChecked.tla, which safe               *)
(* configurations check.  This module deliberately does not assume it, so   *)
(* that TLC can exhibit the lease-exclusivity violation when the bound is   *)
(* not met (see PaxosLeaseUnsafeQuarantine.cfg).  Quarantine does not need  *)
(* to cover the acceptor exclusion duration: a forgotten exclusion matters  *)
(* only through the proposer attempt it supports, and under the             *)
(* prepare-time timer rule that attempt expires ProposerDuration after its  *)
(* Prepare was sent, which is no later than the crash.                      *)
(***************************************************************************)

Ballots0 == Ballots \cup {0}
Owners == Proposers \cup {NoOwner}
MaxDeadline == MaxTime + AcceptorDuration + Quarantine + 1

LeaseRec == [owner : Owners, ballot : Ballots0, deadline : 0..MaxDeadline]
NoLease == [owner |-> NoOwner, ballot |-> 0, deadline |-> 0]

Msg ==
    [kind : {"Prepare"}, from : Proposers, to : Acceptors, ballot : Ballots]
  \cup [kind : {"Promise"}, from : Acceptors, to : Proposers,
        ballot : Ballots, owner : Owners, acceptedBallot : Ballots0,
        acceptedDeadline : 0..MaxDeadline]
  \cup [kind : {"AcceptReq"}, from : Proposers, to : Acceptors,
        ballot : Ballots, owner : Proposers]
  \cup [kind : {"Accepted"}, from : Acceptors, to : Proposers,
        ballot : Ballots, deadline : 0..MaxDeadline]
  \cup [kind : {"Release"}, from : Proposers, to : Acceptors,
        ballot : Ballots]

VARIABLES
    now,
    network,
    promised,
    accepted,
    phase,
    pBallot,
    usedBallots,
    pDeadline,
    pendingDeadline,
    okResp,
    acceptResp,
    active,
    activeBallot,
    cert,
    certDeadline,
    crashedP,
    crashedA,
    quarantineUntil

vars == << now, network, promised, accepted, phase, pBallot, usedBallots, pDeadline,
           pendingDeadline, okResp, acceptResp, active, activeBallot,
           cert, certDeadline, crashedP, crashedA, quarantineUntil >>

IsQuorum(S) ==
    S \subseteq Acceptors /\ Cardinality(S) * 2 > Cardinality(Acceptors)

Cap(t) == IF t > MaxDeadline THEN MaxDeadline ELSE t

ValidLease(r) == r.owner # NoOwner /\ now < r.deadline

ReportLease(a) == IF ValidLease(accepted[a]) THEN accepted[a] ELSE NoLease

CanParticipateA(a) == a \notin crashedA /\ now >= quarantineUntil[a]

(***************************************************************************)
(* With AllowRedeliver, every deliver action nondeterministically leaves the *)
(* delivered message in the network, so the same message can be delivered    *)
(* again at any later time: possible repeated delivery with unbounded        *)
(* redelivery delay. With AllowRedeliver = FALSE delivery consumes the       *)
(* message and the transport is at-most-once by construction. Identical      *)
(* messages sent twice always collapse in the network set either way;        *)
(* redelivery, not multiplicity, is what this constant controls.             *)
(***************************************************************************)
RedeliverChoice == IF AllowRedeliver THEN {TRUE, FALSE} ELSE {FALSE}

(***************************************************************************)
(* With CrashDropsIncoming, the model has connection-lifecycle delivery:   *)
(* messages addressed to a process are discarded both when it crashes      *)
(* (undelivered inbound data dies with the receiver) and when it restarts  *)
(* (anything sent while it was down was queued to a dead connection, and   *)
(* the audited writers discard pending output on disconnect).  Together    *)
(* the two purges guarantee that every delivered message was sent after    *)
(* its addressee's most recent restart, which is what delivery over a      *)
(* freshly established connection means.  Messages FROM a crashed process  *)
(* may survive, since bytes already sent outlive their sender; the         *)
(* asymmetry is deliberate.  FALSE models connectionless delivery, where   *)
(* a message may arrive after its addressee crashed and restarted.         *)
(***************************************************************************)
PurgeInbox(net, dead) ==
    IF CrashDropsIncoming THEN {m \in net : m.to # dead} ELSE net

RunningP(p) == p \notin crashedP

Init ==
    /\ now = 0
    /\ network = {}
    /\ promised = [a \in Acceptors |-> 0]
    /\ accepted = [a \in Acceptors |-> NoLease]
    /\ phase = [p \in Proposers |-> "idle"]
    /\ pBallot = [p \in Proposers |-> 0]
    /\ usedBallots = {}
    /\ pDeadline = [p \in Proposers |-> 0]
    /\ pendingDeadline = [p \in Proposers |-> 0]
    /\ okResp = [p \in Proposers |-> {}]
    /\ acceptResp = [p \in Proposers |-> {}]
    /\ active = {}
    /\ activeBallot = [p \in Proposers |-> 0]
    /\ cert = [p \in Proposers |-> {}]
    /\ certDeadline = [p \in Proposers |-> [a \in Acceptors |-> 0]]
    /\ crashedP = {}
    /\ crashedA = {}
    /\ quarantineUntil = [a \in Acceptors |-> 0]

StartAcquire ==
    \E p \in Proposers, b \in Ballots :
        /\ RunningP(p)
        /\ phase[p] = "idle"
        /\ (p \notin active \/ AllowRenewal)
        /\ b > pBallot[p]
        /\ b \notin usedBallots
        /\ pBallot' = [pBallot EXCEPT ![p] = b]
        /\ usedBallots' = usedBallots \cup {b}
        /\ phase' = [phase EXCEPT ![p] = "preparing"]
        /\ okResp' = [okResp EXCEPT ![p] = {}]
        /\ acceptResp' = [acceptResp EXCEPT ![p] = {}]
        /\ network' = network \cup
            { [kind |-> "Prepare", from |-> p, to |-> a, ballot |-> b] :
                a \in Acceptors }
        /\ UNCHANGED << now, promised, accepted, pDeadline, pendingDeadline,
                        active, activeBallot, cert, certDeadline, crashedP,
                        crashedA, quarantineUntil >>

DeliverPrepare ==
    \E m \in network, keep \in RedeliverChoice :
        /\ m.kind = "Prepare"
        /\ CanParticipateA(m.to)
        /\ LET r == ReportLease(m.to) IN
            /\ network' =
                (IF keep THEN network ELSE network \ {m}) \cup
                (IF m.ballot >= promised[m.to]
                 THEN { [kind |-> "Promise", from |-> m.to, to |-> m.from,
                         ballot |-> m.ballot, owner |-> r.owner,
                         acceptedBallot |-> r.ballot,
                         acceptedDeadline |-> r.deadline] }
                 ELSE {})
            /\ promised' =
                IF m.ballot >= promised[m.to]
                THEN [promised EXCEPT ![m.to] = m.ballot]
                ELSE promised
        /\ UNCHANGED << now, accepted, phase, pBallot, usedBallots, pDeadline,
                        pendingDeadline, okResp, acceptResp,
                        active, activeBallot, cert, certDeadline, crashedP,
                        crashedA, quarantineUntil >>

(***************************************************************************)
(* P2: a promise counts as open if it reports no live lease, or, FOR A       *)
(* RENEWAL ONLY, a lease owned by this proposer. The renewal qualifier       *)
(* checks provenance and has two parts: the proposer must be currently       *)
(* active, and the reported instance must be that exact lease being renewed  *)
(* (its ballot equals the active ballot). A self-owned record under any      *)
(* other ballot is an artifact of an abandoned attempt, installed when that  *)
(* attempt's accept request landed late, possibly overwriting a competitor's *)
(* live lease without revoking the competitor's authority; counting it as    *)
(* open licenses a fresh acquisition while the competitor is still active.   *)
(* TLC exhibits the two-owner execution in 36 states under                   *)
(* PaxosLeaseRetry.cfg when the qualifier is dropped                         *)
(* (counterexamples/StaleOwnerOpen.tla), and no quarantine length prevents   *)
(* it, since the stale accept request can be delayed arbitrarily.            *)
(***************************************************************************)
DeliverPromise ==
    \E m \in network, keep \in RedeliverChoice :
        /\ m.kind = "Promise"
        /\ RunningP(m.to)
        /\ m.ballot = pBallot[m.to]
        /\ network' = IF keep THEN network ELSE network \ {m}
        /\ okResp' =
            [okResp EXCEPT ![m.to] =
                IF m.owner = NoOwner \/ (m.owner = m.to /\ m.to \in active
                                         /\ m.acceptedBallot = activeBallot[m.to])
                THEN @ \cup {m.from}
                ELSE @]
        /\ UNCHANGED << now, promised, accepted, phase, pBallot, usedBallots, pDeadline,
                        pendingDeadline, acceptResp, active, activeBallot,
                        cert, certDeadline, crashedP, crashedA,
                        quarantineUntil >>

SendAccept ==
    \E p \in Proposers :
        /\ RunningP(p)
        /\ phase[p] = "preparing"
        /\ IsQuorum(okResp[p])
        /\ pendingDeadline' = [pendingDeadline EXCEPT ![p] = Cap(now + ProposerDuration)]
        /\ phase' = [phase EXCEPT ![p] = "accepting"]
        /\ acceptResp' = [acceptResp EXCEPT ![p] = {}]
        /\ network' = network \cup
            { [kind |-> "AcceptReq", from |-> p, to |-> a,
                ballot |-> pBallot[p], owner |-> p] : a \in Acceptors }
        /\ UNCHANGED << now, promised, accepted, pBallot, usedBallots, pDeadline,
                        okResp, active, activeBallot, cert,
                        certDeadline, crashedP, crashedA, quarantineUntil >>

(***************************************************************************)
(* A2.  With RefuseLiveOverwrite, the acceptor additionally refuses to     *)
(* replace a live accepted lease of a DIFFERENT owner, even under a higher *)
(* ballot; the refusal is treated exactly like a ballot rejection (no      *)
(* response, promised unchanged).  This is the acceptor-side repair of the *)
(* stale-owner trap: the record a delayed accept request would overwrite   *)
(* stays in place, so a later prepare still reports the live owner.  The   *)
(* cost is availability, bounded by one exclusion interval.  FALSE is the  *)
(* rule of [1] and of both audited implementations.                        *)
(***************************************************************************)
DeliverAcceptReq ==
    \E m \in network, keep \in RedeliverChoice :
        /\ m.kind = "AcceptReq"
        /\ CanParticipateA(m.to)
        /\ LET granted ==
                /\ m.ballot >= promised[m.to]
                /\ \/ ~RefuseLiveOverwrite
                   \/ ~ValidLease(accepted[m.to])
                   \/ accepted[m.to].owner = m.owner
           IN
            /\ network' =
                (IF keep THEN network ELSE network \ {m}) \cup
                (IF granted
                 THEN { [kind |-> "Accepted", from |-> m.to, to |-> m.from,
                         ballot |-> m.ballot,
                         deadline |-> Cap(now + AcceptorDuration)] }
                 ELSE {})
            /\ promised' =
                IF granted
                THEN [promised EXCEPT ![m.to] = m.ballot]
                ELSE promised
            /\ accepted' =
                IF granted
                THEN [accepted EXCEPT ![m.to] =
                        [owner |-> m.owner, ballot |-> m.ballot,
                         deadline |-> Cap(now + AcceptorDuration)]]
                ELSE accepted
        /\ UNCHANGED << now, phase, pBallot, usedBallots, pDeadline, pendingDeadline,
                        okResp, acceptResp, active, activeBallot,
                        cert, certDeadline, crashedP, crashedA,
                        quarantineUntil >>

DeliverAccepted ==
    \E m \in network, keep \in RedeliverChoice :
        /\ m.kind = "Accepted"
        /\ RunningP(m.to)
        /\ m.ballot = pBallot[m.to]
        /\ phase[m.to] = "accepting"
        /\ LET newResp == acceptResp[m.to] \cup {m.from}
               canActivate == IsQuorum(newResp) /\ now < pendingDeadline[m.to]
            IN
            /\ network' = IF keep THEN network ELSE network \ {m}
            /\ acceptResp' = [acceptResp EXCEPT ![m.to] = newResp]
            /\ certDeadline' =
                [certDeadline EXCEPT ![m.to] =
                    [@ EXCEPT ![m.from] = m.deadline]]
            /\ active' = IF canActivate
                         THEN active \cup {m.to}
                         ELSE active
            /\ activeBallot' = IF canActivate
                               THEN [activeBallot EXCEPT ![m.to] = m.ballot]
                               ELSE activeBallot
            /\ pDeadline' = IF canActivate
                            THEN [pDeadline EXCEPT ![m.to] = pendingDeadline[m.to]]
                            ELSE pDeadline
            /\ cert' = IF canActivate
                       THEN [cert EXCEPT ![m.to] = newResp]
                       ELSE cert
            /\ phase' = IF IsQuorum(newResp)
                        THEN [phase EXCEPT ![m.to] = "idle"]
                        ELSE phase
        /\ UNCHANGED << now, promised, accepted, pBallot, usedBallots, pendingDeadline,
                        okResp, crashedP, crashedA,
                        quarantineUntil >>

(***************************************************************************)
(* P5: an attempt that cannot proceed is abandoned.  The proposer returns   *)
(* to "idle" with its state otherwise untouched; a later StartAcquire       *)
(* retries with a fresh, higher ballot.  Abandoning is allowed at any       *)
(* point of an attempt, which subsumes every timeout policy.  Messages of   *)
(* the abandoned attempt may still be in the network; the ballot guards of  *)
(* DeliverPromise and DeliverAccepted discard their responses.  Abandoning  *)
(* does not touch active: giving up a renewal attempt does not surrender    *)
(* the lease the proposer already holds.  This differs from crash and       *)
(* restart, which strips authority; retry keeps the proposer alive          *)
(* throughout.                                                              *)
(***************************************************************************)
AbandonAttempt ==
    \E p \in Proposers :
        /\ AllowAbandon
        /\ RunningP(p)
        /\ phase[p] # "idle"
        /\ phase' = [phase EXCEPT ![p] = "idle"]
        /\ UNCHANGED << now, network, promised, accepted, pBallot, usedBallots,
                        pDeadline, pendingDeadline, okResp, acceptResp, active,
                        activeBallot, cert, certDeadline, crashedP, crashedA,
                        quarantineUntil >>

Release ==
    \E p \in active :
        /\ AllowRelease
        /\ RunningP(p)
        /\ active' = active \ {p}
        /\ network' = network \cup
            { [kind |-> "Release", from |-> p, to |-> a,
                ballot |-> activeBallot[p]] : a \in Acceptors }
        /\ UNCHANGED << now, promised, accepted, phase, pBallot, usedBallots, pDeadline,
                        pendingDeadline, okResp, acceptResp,
                        activeBallot, cert, certDeadline, crashedP, crashedA,
                        quarantineUntil >>

DeliverRelease ==
    \E m \in network, keep \in RedeliverChoice :
        /\ m.kind = "Release"
        /\ CanParticipateA(m.to)
        /\ network' = IF keep THEN network ELSE network \ {m}
        /\ accepted' =
            IF accepted[m.to].owner = m.from /\ accepted[m.to].ballot = m.ballot
            THEN [accepted EXCEPT ![m.to] = NoLease]
            ELSE accepted
        /\ UNCHANGED << now, promised, phase, pBallot, usedBallots, pDeadline,
                        pendingDeadline, okResp, acceptResp,
                        active, activeBallot, cert, certDeadline, crashedP,
                        crashedA, quarantineUntil >>

DropMessage ==
    \E m \in network :
        /\ AllowDrop
        /\ network' = network \ {m}
        /\ UNCHANGED << now, promised, accepted, phase, pBallot, usedBallots, pDeadline,
                        pendingDeadline, okResp, acceptResp,
                        active, activeBallot, cert, certDeadline, crashedP,
                        crashedA, quarantineUntil >>

Tick ==
    /\ now < MaxTime
    /\ LET nn == now + 1 IN
        /\ now' = nn
        /\ active' = {p \in active : nn < pDeadline[p] /\ p \notin crashedP}
    /\ UNCHANGED << network, promised, accepted, phase, pBallot, usedBallots, pDeadline,
                    pendingDeadline, okResp, acceptResp, activeBallot,
                    cert, certDeadline, crashedP, crashedA, quarantineUntil >>

CrashProposer ==
    \E p \in Proposers :
        /\ AllowCrash
        /\ p \notin crashedP
        /\ crashedP' = crashedP \cup {p}
        /\ active' = active \ {p}
        /\ phase' = [phase EXCEPT ![p] = "idle"]
        /\ network' = PurgeInbox(network, p)
        /\ UNCHANGED << now, promised, accepted, pBallot, usedBallots, pDeadline,
                        pendingDeadline, okResp, acceptResp,
                        activeBallot, cert, certDeadline, crashedA,
                        quarantineUntil >>

RestartProposer ==
    \E p \in crashedP :
        /\ AllowCrash
        /\ crashedP' = crashedP \ {p}
        /\ network' = PurgeInbox(network, p)
        /\ UNCHANGED << now, promised, accepted, phase, pBallot,
                        usedBallots, pDeadline, pendingDeadline, okResp,
                        acceptResp, active, activeBallot, cert, certDeadline,
                        crashedA, quarantineUntil >>

CrashAcceptor ==
    \E a \in Acceptors :
        /\ AllowCrash
        /\ a \notin crashedA
        /\ crashedA' = crashedA \cup {a}
        /\ promised' = [promised EXCEPT ![a] = 0]
        /\ accepted' = [accepted EXCEPT ![a] = NoLease]
        /\ network' = PurgeInbox(network, a)
        /\ UNCHANGED << now, phase, pBallot, usedBallots, pDeadline,
                        pendingDeadline, okResp, acceptResp, active,
                        activeBallot, cert, certDeadline, crashedP,
                        quarantineUntil >>

RestartAcceptor ==
    \E a \in crashedA :
        /\ AllowCrash
        /\ crashedA' = crashedA \ {a}
        /\ quarantineUntil' = [quarantineUntil EXCEPT ![a] = Cap(now + Quarantine)]
        /\ network' = PurgeInbox(network, a)
        /\ UNCHANGED << now, promised, accepted, phase, pBallot,
                        usedBallots, pDeadline, pendingDeadline, okResp,
                        acceptResp, active, activeBallot, cert, certDeadline,
                        crashedP >>

StutterAtEnd ==
    /\ now = MaxTime
    /\ UNCHANGED vars

Next ==
    StartAcquire \/ DeliverPrepare \/ DeliverPromise \/ SendAccept \/
    DeliverAcceptReq \/ DeliverAccepted \/ AbandonAttempt \/ Release \/
    DeliverRelease \/ DropMessage \/ Tick \/ CrashProposer \/
    RestartProposer \/ CrashAcceptor \/ RestartAcceptor \/ StutterAtEnd

Spec == Init /\ [][Next]_vars

TypeOK ==
    /\ now \in 0..MaxTime
    /\ network \in SUBSET Msg
    /\ promised \in [Acceptors -> Ballots0]
    /\ accepted \in [Acceptors -> LeaseRec]
    /\ phase \in [Proposers -> {"idle", "preparing", "accepting"}]
    /\ pBallot \in [Proposers -> Ballots0]
    /\ usedBallots \subseteq Ballots
    /\ pDeadline \in [Proposers -> 0..MaxDeadline]
    /\ pendingDeadline \in [Proposers -> 0..MaxDeadline]
    /\ okResp \in [Proposers -> SUBSET Acceptors]
    /\ acceptResp \in [Proposers -> SUBSET Acceptors]
    /\ active \subseteq Proposers
    /\ activeBallot \in [Proposers -> Ballots0]
    /\ cert \in [Proposers -> SUBSET Acceptors]
    /\ certDeadline \in [Proposers -> [Acceptors -> 0..MaxDeadline]]
    /\ crashedP \subseteq Proposers
    /\ crashedA \subseteq Acceptors
    /\ quarantineUntil \in [Acceptors -> 0..MaxDeadline]

AcceptedCoherence ==
    \A a \in Acceptors :
        \/ accepted[a] = NoLease
        \/ /\ accepted[a].owner \in Proposers
           /\ accepted[a].ballot \in Ballots
           /\ accepted[a].deadline \in 1..MaxDeadline

ActiveImpliesUnexpired ==
    \A p \in active : now < pDeadline[p]

LeaseExclusivity ==
    Cardinality(active) <= 1

ActivationHasQuorum ==
    \A p \in active : IsQuorum(cert[p])

TimerContainment ==
    \A p \in active :
        \A a \in cert[p] : pDeadline[p] <= certDeadline[p][a]

QuarantinePreventsParticipation ==
    \A a \in Acceptors :
        now < quarantineUntil[a] => accepted[a] = NoLease /\ promised[a] = 0

ActiveBallotWellFormed ==
    \A p \in active : activeBallot[p] \in Ballots

Safety ==
    TypeOK /\ AcceptedCoherence /\ ActiveImpliesUnexpired /\
    LeaseExclusivity /\ ActivationHasQuorum /\ TimerContainment /\
    QuarantinePreventsParticipation /\ ActiveBallotWellFormed

StateConstraint ==
    Cardinality(network) <= MaxNetwork

====
