#!/bin/bash
# Fetch the audited upstream sources at the exact commits the paper's audit
# section refers to, and record their provenance.  Running this script
# reproduces upstream/ from scratch; upstream/ itself is gitignored.
#
# Both repositories are licensed under the GNU Affero General Public
# License v3 (see upstream/*/LICENSE).  The clones are unmodified; the
# audit reads them and copies nothing into the artifact except quotations
# in the paper and the review bundle.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
UP="$ROOT/upstream"
MANIFEST="$UP/PROVENANCE.md"

KEYSPACE_URL=https://github.com/scalien/keyspace.git
KEYSPACE_SHA=a99f24a81b4f6f8e48f012e4467cc45df7cb7a6a   # 2011-02-04, last commit on master
SCALIENDB_URL=https://github.com/scalien/scaliendb.git
SCALIENDB_SHA=6097814621355dc5be2026fc7ce3625932ce3263  # 2013-02-15, last commit on master

# Files the audit's claims rest on; their checksums go into the manifest so
# a reader can verify that the sources quoted are the sources fetched.
AUDITED_FILES=(
    keyspace/src/Framework/PaxosLease/PLeaseProposer.cpp
    keyspace/src/Framework/PaxosLease/PLeaseAcceptor.cpp
    keyspace/src/Framework/PaxosLease/PLeaseLearner.cpp
    keyspace/src/Framework/PaxosLease/PLeaseState.h
    keyspace/src/Framework/PaxosLease/PLeaseConsts.h
    keyspace/src/Framework/PaxosLease/PaxosLease.cpp
    keyspace/src/Framework/Transport/TCPConn.h
    keyspace/src/Framework/Transport/TransportTCPWriter.cpp
    keyspace/src/Framework/ReplicatedLog/ReplicatedConfig.cpp
    keyspace/src/System/Platform.cpp
    keyspace/src/System/Time_Posix.cpp
    keyspace/src/System/Events/EventLoop.cpp
    scaliendb/src/Framework/Replication/PaxosLease/PaxosLeaseProposer.cpp
    scaliendb/src/Framework/Replication/PaxosLease/PaxosLeaseLearner.cpp
    scaliendb/src/Framework/Replication/PaxosLease/PaxosLease.h
    scaliendb/src/Framework/Replication/PaxosLease/PaxosLease.cpp
    scaliendb/src/Framework/Replication/ReplicationConfig.cpp
    scaliendb/src/Framework/Replication/Quorums/MajorityQuorum.cpp
    scaliendb/src/Framework/TCP/TCPConnection.cpp
    scaliendb/src/System/Time.cpp
    scaliendb/src/System/Events/EventLoop.cpp
    scaliendb/src/Main.cpp
)

fetch() {
    local dir="$1" url="$2" sha="$3"
    if [ ! -d "$UP/$dir/.git" ]; then
        git clone "$url" "$UP/$dir"
    fi
    git -C "$UP/$dir" fetch --quiet origin
    git -C "$UP/$dir" checkout --quiet "$sha"
}

mkdir -p "$UP"
fetch keyspace "$KEYSPACE_URL" "$KEYSPACE_SHA"
fetch scaliendb "$SCALIENDB_URL" "$SCALIENDB_SHA"

{
    echo "# Upstream provenance"
    echo
    echo "Generated by scripts/fetch_upstream.sh on $(date -u +%Y-%m-%d)."
    echo "Both trees are unmodified clones (verify with 'git status')."
    echo
    echo "| repository | url | commit | license |"
    echo "|---|---|---|---|"
    echo "| keyspace | $KEYSPACE_URL | $KEYSPACE_SHA | AGPLv3 |"
    echo "| scaliendb | $SCALIENDB_URL | $SCALIENDB_SHA | AGPLv3 |"
    echo
    echo "SHA-256 of the files the audit quotes:"
    echo
    echo '```'
    (cd "$UP" && sha256sum "${AUDITED_FILES[@]}")
    echo '```'
} > "$MANIFEST"

echo "wrote $MANIFEST"
