"""Generate the counterexample TLA+ variants from the base specification.

Each variant is the base module with exactly one rule weakened.  This script
is the single source of truth for those weakenings: `--write` regenerates the
modules under counterexamples/, and `--check` (used by `make variant-check`)
regenerates them to memory and fails if the checked-in files differ.  That
makes the claim "a copy of the specification with exactly one rule weakened"
mechanically checkable and prevents the variants from drifting as the base
specification evolves.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASE = ROOT / "tla" / "spec" / "PaxosLease.tla"
OUTDIR = ROOT / "tla" / "counterexamples"


def _replace_once(text: str, old: str, new: str, what: str) -> str:
    if text.count(old) != 1:
        raise SystemExit(f"pattern for {what} not found exactly once in base spec")
    return text.replace(old, new, 1)


def late_timer(base: str) -> str:
    """The original 2012 paper's step-3 rule: the pending deadline starts when
    a prepare quorum is in hand, not when Prepare is sent."""
    s = _replace_once(
        base,
        "---- MODULE PaxosLease ----",
        """---- MODULE LateTimer ----
(***************************************************************************)
(* Intentionally weakened variant of spec/PaxosLease.tla, generated by      *)
(* scripts/generate_variants.py.  Do not edit by hand.                      *)
(*                                                                          *)
(* Weakened rule: the proposer starts its pending deadline when it has a    *)
(* prepare quorum in hand and is about to send accept requests (step 3 of   *)
(* the pseudocode in the original 2012 PaxosLease paper), instead of when   *)
(* it sends Prepare.  Nothing then bounds the age of a prepare quorum, so   *)
(* acceptor crash and restart cannot be made safe by any finite quarantine. *)
(* TLC violates LeaseExclusivity under LateTimer.cfg even though the        *)
(* configuration uses the full quarantine bound.                            *)
(***************************************************************************)""",
        "LateTimer module header",
    )
    s = _replace_once(
        s,
        """        /\\ pendingDeadline' = [pendingDeadline EXCEPT ![p] = Cap(now + ProposerDuration)]
        /\\ phase' = [phase EXCEPT ![p] = "preparing"]""",
        """        /\\ phase' = [phase EXCEPT ![p] = "preparing"]""",
        "LateTimer StartAcquire deadline",
    )
    s = _replace_once(
        s,
        """        /\\ UNCHANGED << now, promised, accepted, pDeadline,
                        active, activeBallot, cert, certDeadline, crashedP,
                        crashedA, quarantineUntil >>""",
        """        /\\ UNCHANGED << now, promised, accepted, pDeadline, pendingDeadline,
                        active, activeBallot, cert, certDeadline, crashedP,
                        crashedA, quarantineUntil >>""",
        "LateTimer StartAcquire UNCHANGED",
    )
    s = _replace_once(
        s,
        """        /\\ phase[p] = "preparing"
        /\\ now < pendingDeadline[p]
        /\\ IsQuorum(okResp[p])""",
        """        /\\ phase[p] = "preparing"
        /\\ IsQuorum(okResp[p])
        /\\ pendingDeadline' = [pendingDeadline EXCEPT ![p] = Cap(now + ProposerDuration)]""",
        "LateTimer SendAccept deadline",
    )
    s = _replace_once(
        s,
        """        /\\ UNCHANGED << now, promised, accepted, pBallot, usedBallots, pDeadline,
                        pendingDeadline, okResp, active, activeBallot, cert,
                        certDeadline, crashedP, crashedA, quarantineUntil >>""",
        """        /\\ UNCHANGED << now, promised, accepted, pBallot, usedBallots, pDeadline,
                        okResp, active, activeBallot, cert,
                        certDeadline, crashedP, crashedA, quarantineUntil >>""",
        "LateTimer SendAccept UNCHANGED",
    )
    return s


def owner_only_release(base: str) -> str:
    """Release matches on owner alone, ignoring the ballot."""
    s = _replace_once(
        base,
        "---- MODULE PaxosLease ----",
        """---- MODULE OwnerOnlyRelease ----
(***************************************************************************)
(* Intentionally weakened variant of spec/PaxosLease.tla, generated by      *)
(* scripts/generate_variants.py.  Do not edit by hand.                      *)
(*                                                                          *)
(* Weakened rule: a release message clears any accepted lease of the same   *)
(* owner, ignoring the ballot.  A release delayed past a re-acquisition by  *)
(* the same owner then erases the newer lease instance, acceptors forget    *)
(* their exclusion, and a second proposer can acquire while the first is    *)
(* still active.  TLC violates LeaseExclusivity under OwnerOnlyRelease.cfg. *)
(***************************************************************************)""",
        "OwnerOnlyRelease module header",
    )
    s = _replace_once(
        s,
        """            IF accepted[m.to].owner = m.from /\\ accepted[m.to].ballot = m.ballot
            THEN [accepted EXCEPT ![m.to] = NoLease]""",
        """            IF accepted[m.to].owner = m.from
            THEN [accepted EXCEPT ![m.to] = NoLease]""",
        "OwnerOnlyRelease DeliverRelease match",
    )
    return s


def scalar_quorum_counting(base: str) -> str:
    """Quorum responses are counted by message rather than by distinct
    acceptor identity.  This is the rule both audited implementations use
    (scalar counters in PLeaseProposer.cpp, membership-check-only vote
    objects in MajorityQuorum.cpp); it is sound only under at-most-once
    delivery per response.  No response-retransmission path was found in the
    audited sources, but at-most-once delivery across connection replacement
    is neither proved nor documented.  The duplicating transport itself is not a weakening: it is
    the base module's AllowRedeliver option, switched on in the
    configuration."""
    s = _replace_once(
        base,
        "---- MODULE PaxosLease ----",
        """---- MODULE ScalarQuorumCounting ----
(***************************************************************************)
(* Intentionally weakened variant of spec/PaxosLease.tla, generated by      *)
(* scripts/generate_variants.py.  Do not edit by hand.                      *)
(*                                                                          *)
(* Weakened rule: the proposer counts quorum responses by message instead   *)
(* of by distinct acceptor identity.  The transport that may deliver a      *)
(* response more than once is not part of the weakening; it is the base     *)
(* module's AllowRedeliver option, switched on in the configuration.  This  *)
(* is how both audited implementations count votes; it is sound only under  *)
(* at-most-once delivery per response.  With redelivery possible, a single  *)
(* acceptor's doubled response counts as a quorum, and TLC violates         *)
(* LeaseExclusivity with no crash at all under ScalarQuorumCounting.cfg.    *)
(***************************************************************************)""",
        "ScalarQuorumCounting module header",
    )
    s = _replace_once(
        s,
        """IsQuorum(S) ==
    S \\subseteq Acceptors /\\ Cardinality(S) * 2 > Cardinality(Acceptors)""",
        """IsQuorum(S) ==
    S \\subseteq Acceptors /\\ Cardinality(S) * 2 > Cardinality(Acceptors)

CountIsQuorum(n) == n * 2 > Cardinality(Acceptors)""",
        "ScalarQuorumCounting quorum predicate",
    )
    s = _replace_once(
        s,
        """    /\\ okResp = [p \\in Proposers |-> {}]
    /\\ acceptResp = [p \\in Proposers |-> {}]""",
        """    /\\ okResp = [p \\in Proposers |-> 0]
    /\\ acceptResp = [p \\in Proposers |-> 0]""",
        "ScalarQuorumCounting Init counters",
    )
    s = _replace_once(
        s,
        """        /\\ okResp' = [okResp EXCEPT ![p] = {}]
        /\\ acceptResp' = [acceptResp EXCEPT ![p] = {}]""",
        """        /\\ okResp' = [okResp EXCEPT ![p] = 0]
        /\\ acceptResp' = [acceptResp EXCEPT ![p] = 0]""",
        "ScalarQuorumCounting StartAcquire counter reset",
    )
    s = _replace_once(
        s,
        """        /\\ okResp' =
            [okResp EXCEPT ![m.to] =
                IF m.owner = NoOwner \\/ (m.owner = m.to /\\ m.to \\in active
                                         /\\ m.acceptedBallot = activeBallot[m.to])
                THEN @ \\cup {m.from}
                ELSE @]""",
        """        /\\ okResp' =
            [okResp EXCEPT ![m.to] =
                IF (m.owner = NoOwner \\/ (m.owner = m.to /\\ m.to \\in active
                                          /\\ m.acceptedBallot = activeBallot[m.to]))
                        /\\ @ < Cardinality(Acceptors)
                THEN @ + 1
                ELSE @]""",
        "ScalarQuorumCounting DeliverPromise",
    )
    s = _replace_once(
        s,
        """        /\\ IsQuorum(okResp[p])""",
        """        /\\ CountIsQuorum(okResp[p])""",
        "ScalarQuorumCounting SendAccept quorum test",
    )
    s = _replace_once(
        s,
        """        /\\ acceptResp' = [acceptResp EXCEPT ![p] = {}]""",
        """        /\\ acceptResp' = [acceptResp EXCEPT ![p] = 0]""",
        "ScalarQuorumCounting SendAccept counter reset",
    )
    s = _replace_once(
        s,
        """        /\\ LET newResp == acceptResp[m.to] \\cup {m.from}
               canActivate == IsQuorum(newResp) /\\ now < pendingDeadline[m.to]
            IN""",
        """        /\\ LET newResp == IF acceptResp[m.to] < Cardinality(Acceptors)
                          THEN acceptResp[m.to] + 1
                          ELSE acceptResp[m.to]
               canActivate == CountIsQuorum(newResp) /\\ now < pendingDeadline[m.to]
            IN""",
        "ScalarQuorumCounting DeliverAccepted counting",
    )
    s = _replace_once(
        s,
        """            /\\ cert' = IF canActivate
                       THEN [cert EXCEPT ![m.to] = newResp]
                       ELSE cert
            /\\ phase' = IF IsQuorum(newResp)""",
        """            /\\ cert' = cert
            /\\ phase' = IF CountIsQuorum(newResp)""",
        "ScalarQuorumCounting DeliverAccepted cert",
    )
    s = _replace_once(
        s,
        """    /\\ okResp \\in [Proposers -> SUBSET Acceptors]
    /\\ acceptResp \\in [Proposers -> SUBSET Acceptors]""",
        """    /\\ okResp \\in [Proposers -> 0..Cardinality(Acceptors)]
    /\\ acceptResp \\in [Proposers -> 0..Cardinality(Acceptors)]""",
        "ScalarQuorumCounting TypeOK counters",
    )
    s = _replace_once(
        s,
        """ActivationHasQuorum ==
    \\A p \\in active : IsQuorum(cert[p])""",
        """ActivationHasQuorum ==
    \\* Not meaningful under scalar counting: no acceptor identities are
    \\* recorded, so there is no certificate to check.
    TRUE""",
        "ScalarQuorumCounting ActivationHasQuorum",
    )
    return s


def stale_owner_open(base: str) -> str:
    """A proposer counts a reported lease it owns as open even when it is
    not currently active (not renewing).  This drops P2's renewal
    qualifier.  An accept request from an abandoned attempt, landing late,
    can overwrite a competitor's live lease record with a stale record
    owned by the retrying proposer; counting that record as open licenses
    a fresh acquisition while the competitor is still active.  Both
    audited implementations implement this rule: StartProposing proceeds with
    a full fresh duration whenever the discovered lease owner is the node
    itself (keyspace PLeaseProposer.cpp, scaliendb PaxosLeaseProposer.cpp),
    active or not."""
    s = _replace_once(
        base,
        "---- MODULE PaxosLease ----",
        """---- MODULE StaleOwnerOpen ----
(***************************************************************************)
(* Intentionally weakened variant of spec/PaxosLease.tla, generated by      *)
(* scripts/generate_variants.py.  Do not edit by hand.                      *)
(*                                                                          *)
(* Weakened rule: a proposer counts a reported lease it owns as open even   *)
(* when it is not currently active, dropping P2's renewal qualifier.  With  *)
(* retry enabled (AllowAbandon), an accept request from an abandoned        *)
(* attempt can land late, overwrite a competitor's live lease record, and   *)
(* then license the retrying proposer's fresh acquisition as its "own"      *)
(* lease while the competitor is still active.  TLC violates                *)
(* LeaseExclusivity under StaleOwnerOpen.cfg at the full quarantine bound,  *)
(* and no quarantine length prevents the execution, since the stale accept  *)
(* request can be delayed arbitrarily.                                      *)
(***************************************************************************)""",
        "StaleOwnerOpen module header",
    )
    s = _replace_once(
        s,
        """                IF m.owner = NoOwner \\/ (m.owner = m.to /\\ m.to \\in active
                                         /\\ m.acceptedBallot = activeBallot[m.to])
                THEN @ \\cup {m.from}""",
        """                IF m.owner = NoOwner \\/ m.owner = m.to
                THEN @ \\cup {m.from}""",
        "StaleOwnerOpen DeliverPromise qualifier",
    )
    return s


VARIANTS = {
    "LateTimer.tla": late_timer,
    "OwnerOnlyRelease.tla": owner_only_release,
    "ScalarQuorumCounting.tla": scalar_quorum_counting,
    "StaleOwnerOpen.tla": stale_owner_open,
}


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate the variant modules")
    mode.add_argument("--check", action="store_true", help="fail if checked-in variants differ")
    args = parser.parse_args()

    base = BASE.read_text(encoding="utf-8")
    failures = []
    for name, fn in VARIANTS.items():
        generated = fn(base)
        path = OUTDIR / name
        if args.write:
            path.write_text(generated, encoding="utf-8")
            print(f"wrote {path}")
        else:
            on_disk = path.read_text(encoding="utf-8") if path.exists() else ""
            if on_disk != generated:
                failures.append(name)
            else:
                print(f"{name}: matches base + declared weakening")
    if failures:
        print(f"variant drift detected: {failures}", file=sys.stderr)
        print("run scripts/generate_variants.py --write to regenerate", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
